global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8000"]
  - job_name: "scaledown-client"
    metrics_path: /metrics
    static_configs:
      - targets: ["scaledown-client:8000"]
